"use client";

import { useEffect, useMemo, useState } from "react";
import CytoscapeComponent from "react-cytoscapejs";
import ReactECharts from "echarts-for-react";
import { BarChart3, CalendarDays, Database, Network, Search, SlidersHorizontal, TableProperties } from "lucide-react";

type TabId = "corpus" | "network" | "compare" | "evidence";
type CorpusDocument = { document_id: string; published_at: string; year: number; month: string; channel: string; platform: string | null; content_type: string | null; title: string | null; url: string | null; event_id: string; event_name: string; ponzi: boolean; subsidi: boolean; biaya_haji: boolean; dana_haji: boolean; nilai_manfaat: boolean; antrean_haji: boolean };
type Edge = { statement_id: string; document_id: string; published_at: string; year: number; channel: string; platform: string | null; event_id: string; event_name: string; actor: string; actor_normalized?: string; concept: string; proposition: string; stance: "support" | "oppose"; sign: number; statement_text: string; context_text: string; url: string | null; source_locator: string; stance_score: number; actor_confidence: string; actor_method: string };
type EventWindow = { event_id: string; event_name: string; start_date: string; end_date: string; selection_basis: string };
type Dataset = { corpus: CorpusDocument[]; documentEdges: Edge[]; statements: Edge[]; events: EventWindow[] };
type Filters = { startDate: string; endDate: string; channel: string; platform: string; eventId: string; concept: string; stance: string; actorQuery: string };

const INITIAL_FILTERS: Filters = { startDate: "2021-01-01", endDate: "2024-12-31", channel: "all", platform: "all", eventId: "all", concept: "all", stance: "all", actorQuery: "" };
const TABS: { id: TabId; label: string; icon: typeof Database; description: string }[] = [
  { id: "corpus", label: "Korpus & Waktu", icon: Database, description: "Cakupan sumber dan dinamika waktu" },
  { id: "network", label: "Jaringan Wacana", icon: Network, description: "Relasi aktor, konsep, dan posisi" },
  { id: "compare", label: "Perbandingan", icon: BarChart3, description: "Dua periode atau arena" },
  { id: "evidence", label: "Pernyataan & Bukti", icon: TableProperties, description: "Teks dan jejak sumber" },
];
const LEXICAL_TERMS = [["ponzi", "Ponzi"], ["biaya_haji", "Biaya haji"], ["subsidi", "Subsidi"], ["dana_haji", "Dana haji"], ["nilai_manfaat", "Nilai manfaat"], ["antrean_haji", "Antrean haji"]] as const;
const CONCEPT_LABELS: Record<string, string> = { ponzi: "Ponzi", kenaikan_biaya: "Kenaikan biaya", keamanan_dana: "Keamanan dana", keadilan: "Keadilan", keberlanjutan: "Keberlanjutan", subsidi_silang: "Subsidi silang" };

const formatNumber = (value: number) => new Intl.NumberFormat("id-ID").format(value);
const formatChannel = (value: string) => value === "media_massa" ? "Media massa" : "Media sosial";
const inRange = (date: string, filters: Filters) => date.slice(0, 10) >= filters.startDate && date.slice(0, 10) <= filters.endDate;
function matchesBase(row: { published_at: string; channel: string; platform: string | null; event_id: string }, filters: Filters) { return inRange(row.published_at, filters) && (filters.channel === "all" || row.channel === filters.channel) && (filters.platform === "all" || row.platform === filters.platform) && (filters.eventId === "all" || row.event_id === filters.eventId); }
function matchesEdge(edge: Edge, filters: Filters) { const actor = (edge.actor_normalized || edge.actor).toLowerCase(); return matchesBase(edge, filters) && (filters.concept === "all" || edge.concept === filters.concept) && (filters.stance === "all" || edge.stance === filters.stance) && (!filters.actorQuery || actor.includes(filters.actorQuery.toLowerCase())); }
function Card({ label, value, note }: { label: string; value: string; note: string }) { return <article className="metric-card"><span>{label}</span><strong>{value}</strong><small>{note}</small></article>; }

function FilterBar({ dataset, filters, setFilters }: { dataset: Dataset; filters: Filters; setFilters: (filters: Filters) => void }) {
  const platforms = useMemo(() => Array.from(new Set(dataset.corpus.map((row) => row.platform).filter(Boolean))).sort() as string[], [dataset.corpus]);
  const concepts = useMemo(() => Array.from(new Set(dataset.documentEdges.map((row) => row.concept))).sort(), [dataset.documentEdges]);
  const update = (field: keyof Filters, value: string) => setFilters({ ...filters, [field]: value });
  return <section className="filters" aria-label="Filter data"><div className="filter-heading"><SlidersHorizontal size={16} /> Filter bersama</div><label>Tanggal<input type="date" value={filters.startDate} onChange={(event) => update("startDate", event.target.value)} /></label><label>Sampai<input type="date" value={filters.endDate} onChange={(event) => update("endDate", event.target.value)} /></label><label>Kanal<select value={filters.channel} onChange={(event) => update("channel", event.target.value)}><option value="all">Semua kanal</option><option value="media_massa">Media massa</option><option value="media_sosial">Media sosial</option></select></label><label>Platform<select value={filters.platform} onChange={(event) => update("platform", event.target.value)}><option value="all">Semua platform</option>{platforms.map((item) => <option key={item} value={item}>{item}</option>)}</select></label><label>Event window<select value={filters.eventId} onChange={(event) => update("eventId", event.target.value)}><option value="all">Semua periode</option><option value="outside_windows">Di luar event window</option>{dataset.events.map((event) => <option key={event.event_id} value={event.event_id}>{event.event_id}</option>)}</select></label><label>Konsep<select value={filters.concept} onChange={(event) => update("concept", event.target.value)}><option value="all">Semua konsep</option>{concepts.map((item) => <option key={item} value={item}>{CONCEPT_LABELS[item] || item}</option>)}</select></label><label>Stance<select value={filters.stance} onChange={(event) => update("stance", event.target.value)}><option value="all">Support dan oppose</option><option value="support">Support</option><option value="oppose">Oppose</option></select></label><label className="actor-search"><Search size={15} /><input value={filters.actorQuery} onChange={(event) => update("actorQuery", event.target.value)} placeholder="Cari aktor" /></label><button className="reset-button" onClick={() => setFilters(INITIAL_FILTERS)}>Reset</button></section>;
}

function CorpusTab({ corpus, edges, events, filters, setFilters }: { corpus: CorpusDocument[]; edges: Edge[]; events: EventWindow[]; filters: Filters; setFilters: (filters: Filters) => void }) {
  const months = useMemo(() => Array.from(new Set(corpus.map((row) => row.month))).sort(), [corpus]);
  const trendOption = useMemo(() => ({ tooltip: { trigger: "axis" }, legend: { bottom: 0, data: ["Media massa", "Media sosial"] }, grid: { left: 45, right: 24, top: 32, bottom: 48 }, xAxis: { type: "category", data: months, axisLabel: { rotate: 38, formatter: (value: string) => value.slice(0, 7) } }, yAxis: { type: "value", name: "Dokumen" }, series: ["media_massa", "media_sosial"].map((channel, index) => ({ name: formatChannel(channel), type: "line", smooth: true, symbolSize: 5, lineStyle: { width: 2 }, itemStyle: { color: index === 0 ? "#3468c0" : "#d9653b" }, data: months.map((month) => corpus.filter((row) => row.month === month && row.channel === channel).length) })) }), [corpus, months]);
  const termOption = useMemo(() => { const data = LEXICAL_TERMS.map(([field, label]) => ({ label, value: corpus.filter((row) => row[field]).length })); return { tooltip: { trigger: "axis" }, grid: { left: 90, right: 24, top: 20, bottom: 28 }, xAxis: { type: "value" }, yAxis: { type: "category", data: data.map((item) => item.label) }, series: [{ type: "bar", data: data.map((item) => item.value), itemStyle: { color: "#be8a34", borderRadius: [0, 5, 5, 0] } }] }; }, [corpus]);
  const networkDocuments = new Set(edges.map((edge) => edge.document_id));
  return <><section className="page-intro"><p className="eyebrow">01 / Cakupan analisis</p><h1>Korpus dan dinamika waktu</h1><p>Mulai dari sumber: berapa banyak dokumen tercakup, kapan pembicaraan meningkat, dan peristiwa mana yang membingkai pembacaan jaringan.</p></section><section className="metrics-grid"><Card label="Dokumen unik" value={formatNumber(corpus.length)} note="sesuai filter aktif" /><Card label="Dokumen dengan relasi DNA" value={formatNumber(networkDocuments.size)} note="memiliki setidaknya satu relasi terkode" /><Card label="Media massa" value={formatNumber(corpus.filter((row) => row.channel === "media_massa").length)} note="dokumen pada cakupan aktif" /><Card label="Media sosial" value={formatNumber(corpus.filter((row) => row.channel === "media_sosial").length)} note="dokumen pada cakupan aktif" /></section><section className="chart-grid corpus-grid"><article className="panel chart-panel"><div className="panel-heading"><div><h2>Volume dokumen per bulan</h2><p>Unit: dokumen unik; kanal dipisahkan agar tidak saling menutupi.</p></div><CalendarDays size={20} /></div><ReactECharts option={trendOption} style={{ height: 330 }} /></article><article className="panel chart-panel"><div className="panel-heading"><div><h2>Penyebutan istilah</h2><p>Indikator leksikal pada dokumen, bukan stance DNA.</p></div></div><ReactECharts option={termOption} style={{ height: 330 }} /></article></section><section className="panel"><div className="panel-heading"><div><h2>Event window</h2><p>Periode substantif yang didefinisikan sebelum pembacaan hasil jaringan.</p></div></div><div className="event-list">{events.map((event) => <button key={event.event_id} className="event-card" onClick={() => setFilters({ ...filters, startDate: event.start_date, endDate: event.end_date, eventId: event.event_id })}><span>{event.event_id}</span><strong>{event.event_name}</strong><small>{event.start_date} — {event.end_date}</small></button>)}</div></section></>;
}

function NetworkGraph({ edges, onSelect }: { edges: Edge[]; onSelect: (label: string) => void }) {
  const elements = useMemo(() => { const unique = new Map<string, { actor: string; concept: string; stance: string; count: number }>(); edges.forEach((edge) => { const actor = edge.actor_normalized || edge.actor; const key = `${actor}|${edge.concept}|${edge.stance}`; const current = unique.get(key) || { actor, concept: edge.concept, stance: edge.stance, count: 0 }; current.count += 1; unique.set(key, current); }); const actors = Array.from(new Set(edges.map((edge) => edge.actor_normalized || edge.actor))); const concepts = Array.from(new Set(edges.map((edge) => edge.concept))); return [...actors.map((actor) => ({ data: { id: `actor:${actor}`, label: actor }, classes: "actor" })), ...concepts.map((concept) => ({ data: { id: `concept:${concept}`, label: CONCEPT_LABELS[concept] || concept }, classes: "concept" })), ...Array.from(unique.values()).map((edge) => ({ data: { id: `edge:${edge.actor}:${edge.concept}:${edge.stance}`, source: `actor:${edge.actor}`, target: `concept:${edge.concept}`, weight: edge.count }, classes: edge.stance }))]; }, [edges]);
  const stylesheet = [{ selector: "node", style: { label: "data(label)", "font-size": 10, color: "#253145", "text-wrap": "wrap", "text-max-width": 90, "text-valign": "center", "text-halign": "center", width: 42, height: 42 } }, { selector: ".actor", style: { "background-color": "#3468c0", color: "#203552", "text-margin-y": -30 } }, { selector: ".concept", style: { "background-color": "#d9a441", shape: "round-rectangle", width: 76, height: 42, color: "#4b3510", "text-margin-y": -32 } }, { selector: "edge", style: { width: "mapData(weight, 1, 20, 1.5, 8)", opacity: 0.8, "curve-style": "bezier" } }, { selector: ".support", style: { "line-color": "#278b6c", "line-style": "solid" } }, { selector: ".oppose", style: { "line-color": "#d4514c", "line-style": "dashed" } }];
  return <CytoscapeComponent elements={elements} stylesheet={stylesheet} layout={{ name: "cose", animate: false, padding: 46, nodeRepulsion: 850000, idealEdgeLength: 145 }} style={{ width: "100%", height: "530px" }} cy={(cy) => cy.on("tap", "node", (event) => onSelect(event.target.data("label")))} />;
}

function NetworkTab({ edges, openEvidence }: { edges: Edge[]; openEvidence: (filters: Partial<Filters>) => void }) {
  const [selected, setSelected] = useState(""); const actors = new Set(edges.map((edge) => edge.actor_normalized || edge.actor)); const concepts = Array.from(new Set(edges.map((edge) => edge.concept))).sort(); const matrixActors = Array.from(actors).sort((a, b) => edges.filter((edge) => (edge.actor_normalized || edge.actor) === b).length - edges.filter((edge) => (edge.actor_normalized || edge.actor) === a).length).slice(0, 16); const selectedEdges = edges.filter((edge) => (edge.actor_normalized || edge.actor) === selected || edge.concept === selected);
  return <><section className="page-intro"><p className="eyebrow">02 / Struktur wacana</p><h1>Jaringan aktor dan signifier</h1><p>Setiap garis adalah relasi terkode dalam dokumen: hijau untuk support dan merah putus-putus untuk oppose.</p></section><section className="metrics-grid"><Card label="Relasi tingkat dokumen" value={formatNumber(edges.length)} note="satu relasi per dokumen" /><Card label="Aktor" value={formatNumber(actors.size)} note="aktor yang muncul dalam jaringan" /><Card label="Konsep" value={formatNumber(concepts.length)} note="signifier/konsep dari codebook" /><Card label="Pernyataan terpilih" value={formatNumber(new Set(edges.map((edge) => edge.statement_id)).size)} note="bukti di balik relasi" /></section><section className="network-layout"><article className="panel network-panel"><div className="panel-heading"><div><h2>Jaringan bipartit</h2><p>Ukuran garis: jumlah dokumen pada pasangan aktor–konsep–stance.</p></div><div className="legend"><span><i className="actor-dot" /> Aktor</span><span><i className="concept-dot" /> Konsep</span><span><i className="support-line" /> Support</span><span><i className="oppose-line" /> Oppose</span></div></div><NetworkGraph edges={edges} onSelect={setSelected} /></article><aside className="panel detail-panel"><p className="eyebrow">Detail pilihan</p>{selected ? <><h2>{selected}</h2><p>{selectedEdges.length} relasi sesuai filter aktif.</p><div className="detail-stats"><span>Support <strong>{selectedEdges.filter((edge) => edge.stance === "support").length}</strong></span><span>Oppose <strong>{selectedEdges.filter((edge) => edge.stance === "oppose").length}</strong></span></div><button className="primary-button" onClick={() => openEvidence(CONCEPT_LABELS[selected] ? { concept: selected } : { actorQuery: selected })}>Buka bukti</button></> : <><h2>Pilih node</h2><p>Klik aktor atau konsep pada jaringan untuk melihat ringkasan relasi dan membuka bukti tekstualnya.</p></>}</aside></section><section className="panel matrix-panel"><div className="panel-heading"><div><h2>Matriks posisi aktor</h2><p>Angka hijau menunjukkan support; angka merah menunjukkan oppose. Ditampilkan 16 aktor dengan relasi terbanyak.</p></div></div><div className="table-scroll"><table><thead><tr><th>Aktor</th>{concepts.map((concept) => <th key={concept}>{CONCEPT_LABELS[concept]}</th>)}</tr></thead><tbody>{matrixActors.map((actor) => <tr key={actor}><td><button className="table-link" onClick={() => setSelected(actor)}>{actor}</button></td>{concepts.map((concept) => { const rows = edges.filter((edge) => (edge.actor_normalized || edge.actor) === actor && edge.concept === concept); return <td key={concept}><span className="support-count">+{rows.filter((edge) => edge.stance === "support").length}</span><span className="oppose-count">−{rows.filter((edge) => edge.stance === "oppose").length}</span></td>; })}</tr>)}</tbody></table></div></section></>;
}

function ComparisonTab({ edges, events }: { edges: Edge[]; events: EventWindow[] }) {
  const [groupA, setGroupA] = useState("E1_BPIH_2023"); const [groupB, setGroupB] = useState("E3_NILAI_MANFAAT"); const a = edges.filter((edge) => edge.event_id === groupA); const b = edges.filter((edge) => edge.event_id === groupB); const concepts = Array.from(new Set(edges.map((edge) => edge.concept))).sort(); const option = { tooltip: { trigger: "axis" }, legend: { bottom: 0 }, grid: { left: 58, right: 26, top: 30, bottom: 50 }, xAxis: { type: "category", data: concepts.map((concept) => CONCEPT_LABELS[concept]) }, yAxis: { type: "value", name: "Relasi" }, series: [{ name: "A · support", type: "bar", stack: "A", data: concepts.map((concept) => a.filter((edge) => edge.concept === concept && edge.stance === "support").length), itemStyle: { color: "#278b6c" } }, { name: "A · oppose", type: "bar", stack: "A", data: concepts.map((concept) => a.filter((edge) => edge.concept === concept && edge.stance === "oppose").length), itemStyle: { color: "#d4514c" } }, { name: "B · support", type: "bar", stack: "B", data: concepts.map((concept) => b.filter((edge) => edge.concept === concept && edge.stance === "support").length), itemStyle: { color: "#6da892" } }, { name: "B · oppose", type: "bar", stack: "B", data: concepts.map((concept) => b.filter((edge) => edge.concept === concept && edge.stance === "oppose").length), itemStyle: { color: "#e49a93" } }] }; const nameFor = (id: string) => events.find((event) => event.event_id === id)?.event_name || "Event window";
  return <><section className="page-intro"><p className="eyebrow">03 / Perubahan konfigurasi</p><h1>Bandingkan dua event window</h1><p>Bandingkan komposisi posisi pada dua periode dengan unit relasi tingkat dokumen yang sama.</p></section><section className="comparison-selectors"><label>Kelompok A<select value={groupA} onChange={(event) => setGroupA(event.target.value)}>{events.map((event) => <option key={event.event_id} value={event.event_id}>{event.event_id} · {event.event_name}</option>)}</select></label><label>Kelompok B<select value={groupB} onChange={(event) => setGroupB(event.target.value)}>{events.map((event) => <option key={event.event_id} value={event.event_id}>{event.event_id} · {event.event_name}</option>)}</select></label></section><section className="metrics-grid"><Card label="Relasi A" value={formatNumber(a.length)} note={nameFor(groupA)} /><Card label="Aktor A" value={formatNumber(new Set(a.map((edge) => edge.actor_normalized || edge.actor)).size)} note="dalam jaringan A" /><Card label="Relasi B" value={formatNumber(b.length)} note={nameFor(groupB)} /><Card label="Aktor B" value={formatNumber(new Set(b.map((edge) => edge.actor_normalized || edge.actor)).size)} note="dalam jaringan B" /></section><section className="panel chart-panel"><div className="panel-heading"><div><h2>Komposisi stance per konsep</h2><p>Setiap warna mewakili jumlah relasi, bukan skor neto.</p></div></div><ReactECharts option={option} style={{ height: 390 }} /></section><section className="panel"><div className="panel-heading"><div><h2>Perubahan yang perlu dibaca</h2><p>Daftar ringkas ini mengarahkan kembali ke pernyataan sumber.</p></div></div><div className="comparison-list">{concepts.map((concept) => <div key={concept}><strong>{CONCEPT_LABELS[concept]}</strong><span>A: {a.filter((edge) => edge.concept === concept).length} relasi</span><span>B: {b.filter((edge) => edge.concept === concept).length} relasi</span></div>)}</div></section></>;
}

function EvidenceTab({ statements }: { statements: Edge[] }) { const [selectedId, setSelectedId] = useState(statements[0]?.statement_id || ""); const selected = statements.find((statement) => statement.statement_id === selectedId) || statements[0]; return <><section className="page-intro"><p className="eyebrow">04 / Audit dan pembacaan</p><h1>Pernyataan dan bukti</h1><p>Gunakan tab ini untuk memeriksa teks yang membentuk relasi pada jaringan. Stance selalu dibaca terhadap proposisi yang tampil di bawahnya.</p></section><section className="evidence-layout"><article className="panel evidence-list"><div className="panel-heading"><div><h2>{formatNumber(statements.length)} pernyataan</h2><p>Hasil sesuai filter aktif.</p></div></div><div className="statement-list">{statements.slice(0, 100).map((statement) => <button key={statement.statement_id} className={`statement-row ${selected?.statement_id === statement.statement_id ? "selected" : ""}`} onClick={() => setSelectedId(statement.statement_id)}><span className={`stance-badge ${statement.stance}`}>{statement.stance}</span><strong>{statement.actor}</strong><em>{CONCEPT_LABELS[statement.concept]}</em><p>{statement.statement_text}</p><small>{statement.published_at.slice(0, 10)} · {formatChannel(statement.channel)}</small></button>)}</div></article>{selected && <aside className="panel reader-panel"><p className="eyebrow">Pernyataan terpilih</p><div className="reader-meta"><span className={`stance-badge ${selected.stance}`}>{selected.stance}</span><span>{selected.actor}</span><span>{CONCEPT_LABELS[selected.concept]}</span></div><h2>{selected.proposition}</h2><blockquote>{selected.statement_text}</blockquote><p className="context-text">{selected.context_text}</p><dl><div><dt>Tanggal</dt><dd>{selected.published_at}</dd></div><div><dt>Event window</dt><dd>{selected.event_name}</dd></div><div><dt>Metode aktor</dt><dd>{selected.actor_method}</dd></div><div><dt>Skor stance</dt><dd>{selected.stance_score.toFixed(3)}</dd></div><div><dt>Locator</dt><dd>{selected.source_locator}</dd></div></dl>{selected.url && <a className="source-link" href={selected.url} target="_blank" rel="noreferrer">Buka sumber asli</a>}</aside>}</section></>; }

export default function Home() { const [dataset, setDataset] = useState<Dataset | null>(null); const [tab, setTab] = useState<TabId>("corpus"); const [filters, setFilters] = useState<Filters>(INITIAL_FILTERS); useEffect(() => { Promise.all([fetch("/data/corpus.json").then((response) => response.json()), fetch("/data/document_edges.json").then((response) => response.json()), fetch("/data/statements.json").then((response) => response.json()), fetch("/data/event_windows.json").then((response) => response.json())]).then(([corpus, documentEdges, statements, events]) => setDataset({ corpus, documentEdges, statements, events })); }, []); if (!dataset) return <main className="loading-screen"><div><p className="eyebrow">DISCOURSE NETWORK ANALYSIS</p><h1>Memuat korpus riset…</h1><p>Menyiapkan data dokumen, relasi, dan bukti sumber.</p></div></main>; const filteredCorpus = dataset.corpus.filter((row) => matchesBase(row, filters)); const filteredEdges = dataset.documentEdges.filter((edge) => matchesEdge(edge, filters)); const filteredStatements = dataset.statements.filter((statement) => matchesEdge(statement, filters)); const comparisonEdges = dataset.documentEdges.filter((edge) => inRange(edge.published_at, filters) && (filters.channel === "all" || edge.channel === filters.channel) && (filters.platform === "all" || edge.platform === filters.platform)); const openEvidence = (next: Partial<Filters>) => { setFilters({ ...filters, ...next }); setTab("evidence"); }; return <main className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">DNA</span><div><strong>Wacana Haji</strong><small>2021–2024</small></div></div><nav>{TABS.map(({ id, label, icon: Icon, description }) => <button key={id} className={tab === id ? "nav-item active" : "nav-item"} onClick={() => setTab(id)}><Icon size={19} /><span>{label}<small>{description}</small></span></button>)}</nav><div className="sidebar-note"><p>Unit jaringan</p><strong>Aktor × konsep × stance</strong><span>Satu relasi per dokumen</span></div></aside><section className="workspace"><header><div><p className="eyebrow">DASHBOARD EKSPLORASI</p><h2>Kontestasi pembiayaan haji</h2></div><span className="status-dot">Data turunan v1</span></header><FilterBar dataset={dataset} filters={filters} setFilters={setFilters} /><div className="page-content">{tab === "corpus" && <CorpusTab corpus={filteredCorpus} edges={filteredEdges} events={dataset.events} filters={filters} setFilters={setFilters} />}{tab === "network" && <NetworkTab edges={filteredEdges} openEvidence={openEvidence} />}{tab === "compare" && <ComparisonTab edges={comparisonEdges} events={dataset.events} />}{tab === "evidence" && <EvidenceTab statements={filteredStatements} />}</div></section></main>; }
